Comercial/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include('Ecom.urls')),
    path('' , include('users.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Ecom/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('' , views.home , name="home"),
    path('product/<int:pk>/' , views.product_detail , name="product-detail"),
    path('newproduct/' , views.NewProduct , name="new-product"),
    path('mysellership/' , views.cancel_sellership , name='cancel-sellership'),
    path('getsellership/' , views.get_sellership , name="get-sellership"),    
    path('confirmsellership/' , views.confirm_sellership , name="confirm-sellership"),
    path('advisesellership/' , views.get_sellership_advise , name="sellership-advise"),
    path('deposit/' , views.deposit , name="user-deposit"),
    path('successfuldeposit' , views.successful_deposit , name="successful-deposit"),
    path('search/' , views.search_bar , name="search"),
    path('added/<int:pk>/' , views.add_to_cart , name="add-cart"),
    path('cart/' , views.user_cart , name="user-cart"),
    path('cart/delete/<int:pk>/' , views.delete_cart_items , name="delete-cart"),
    path('payment/' , views.proceed_payment , name="proceed-payment"),
    path('payment/successful_payment' , views.successful_payment , name="successful-payment"),
    path('my_products/' , views.my_products , name="my-products"),
    path('seller_orders/' , views.seller_orders , name="seller-orders"),
    path('edit_product/<int:pk>/' , views.edit_product , name="edit-product"),
    path('confirmed_edit/<int:pk>/' , views.confirm_edit , name="confirm-edit"),
    path('delete_product/<int:pk>/' , views.delete_product , name="delete-product"),
    path('order_detail/<int:pk>/' , views.order_detail , name="order-detail"),
    path('tracking_number/<int:pk>' , views.tracking_number , name="tracking-number"),
    path('my_orders/' , views.my_orders , name="my-orders"),
    path('review/<int:pk>/' , views.confirm_review , name="review-confirmation")
]

Ecom/models.py
from django.shortcuts import reverse
from django.db import models
from users.models import User , Profile
from django.core.validators import MinValueValidator , MaxValueValidator
from PIL import Image
from django.dispatch import receiver
from django.utils import timezone

class Product(models.Model):
    one_day = '1 Day'
    two_days = '2 Days'
    three_days = '3 Days'
    four_days = '4 Days'
    five_days = '5 Days'
    six_days = '6 Days'
    seven_days = '7 Days'
    SHIPMENT_TIME_CHOICE = [
        (one_day ,'1 Day'),
        (two_days , '2 Days'),
        (three_days , '3 Days'),
        (four_days , '4 Days'),
        (five_days , '5 Days'),
        (six_days , '6 Days'),
        (seven_days , '7 Days'),
    ]
    
    title = models.CharField(max_length=100)    
    content = models.TextField()    
    seller = models.ForeignKey(User , on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=8 , decimal_places=2 , validators=[MinValueValidator(0.5)] , default=0)    
    shipping_price = models.DecimalField(max_digits=8 , decimal_places=2 , validators=[MinValueValidator(-0.00)] , default=0)
    shipping_time = models.CharField(choices=SHIPMENT_TIME_CHOICE , max_length=7 , blank=False , default=seven_days)
    stock = models.IntegerField(default=1 , blank=False)
    clicks_count = models.IntegerField(default = 0)
    clicks = models.ManyToManyField(User , related_name="clicks" , blank=True)
    show = models.BooleanField(default=True)
    image1 = models.ImageField(blank=False , default='3i1415926543PI.jpg' , upload_to='images')
    image2 = models.ImageField(default=None , blank=True , upload_to='images')
    image3 = models.ImageField(default=None , blank=True , upload_to='images')

    def save(self , *args , **kwargs):
        super(Product, self).save(*args , **kwargs)

        img1 = Image.open(self.image1.path)
        if self.image2:
            img2 = Image.open(self.image2.path)
            img2.save(self.image2.path)
        else:
            pass
        if self.image3:
            img3 = Image.open(self.image3.path)
            img3.save(self.image3.path)
    
    def get_absolute_url(self):
        return reverse("product-detail", kwargs={"pk": self.pk})
    
    def __str__(self):
        if self.show == False:
            return self.title + " --> Closed"
        elif self.show == True:
            return self.title

class AddCart(models.Model):
    buyer = models.ForeignKey(User , on_delete=models.CASCADE)
    item = models.ForeignKey(Product , on_delete=models.CASCADE)
    number = models.IntegerField(default=1 , validators=[MinValueValidator(1)])
    show = models.BooleanField(default=True)

    def true_price(self):
        price = self.item.price
        quantity = self.number
        return price * quantity

    def true_price_plus_shipping_price(self):
        price = self.item.price
        shipping_price = self.item.shipping_price
        quantity = self.number
        return (price * quantity) + shipping_price


    def __str__(self):
        return "{} added {} to cart".format(self.buyer , self.item)

class Review(models.Model):
    zero_stars = 0
    one_star = 1
    two_stars = 2
    three_stars = 3
    four_stars = 4
    five_stars = 5

    STAR_RATING_CHOICE = [
        (zero_stars , 0 ),
        (one_star , 1),
        (two_stars , 2),
        (three_stars , 3),
        (four_stars , 4),
        (five_stars , 5),
    ]
    
    customer = models.ForeignKey(User , on_delete=models.CASCADE)
    item = models.ForeignKey(Product , on_delete=models.CASCADE)
    title = models.CharField(max_length=100 , default="Title of your Review")
    content = models.TextField(max_length=800 , blank=False , default='What do you think about this product?')
    date_reviewed = models.DateTimeField(default=timezone.now)
    rating = models.IntegerField( choices=STAR_RATING_CHOICE , blank = False , validators=[MinValueValidator(-0.00) , MaxValueValidator(5)])
    show = models.BooleanField(default=True)

    def __str__(self):
        return '{} reviewed {}'.format(self.customer , self.item)

class Order(models.Model):
    order_dispatched = 'Order dispatched'
    not_shipped = 'Not shipped'

    ORDER_STATUS_CHOICE = [
        (not_shipped , 'Not shipped'),
        (order_dispatched , 'Order dispatched'),
    ]

    order_status = models.CharField(choices=ORDER_STATUS_CHOICE , default=not_shipped , max_length=100)
    first_track_code = models.BooleanField(default=True)
    order_number = models.CharField(max_length=20 , blank=False , default="Error")
    tracking_number = models.CharField(max_length=200 , blank=True , default="Not Provided Yet")
    ordered_items = models.ForeignKey(AddCart , on_delete=models.CASCADE)
    buyer = models.ForeignKey(User , related_name="buyer" , on_delete=models.CASCADE)    
    seller = models.ForeignKey(User , related_name="seller" , on_delete = models.CASCADE)
    address_line_1 = models.CharField(max_length=100 , blank=False)
    address_line_2 = models.CharField(max_length=100 , blank=True)
    Country = models.CharField(max_length=20)
    state = models.CharField(max_length=20)
    city = models.CharField(max_length=20)
    ZIP_code = models.CharField(max_length=20)
    viewed = models.BooleanField(default=False)
    date_placed = models.DateTimeField(default=timezone.now)
    price_paid = models.DecimalField(max_digits=8 , decimal_places=2 , validators=[MinValueValidator] , blank=False , default=0.10)
    price_seller_received = models.DecimalField(max_digits=8 , decimal_places=2 , validators=[MinValueValidator(-0.00)] , blank=False , default=0.10 )

    def __str__(self):
        return '{} ordered {}'.format(self.buyer , self.ordered_items.item)
    

    
    

Ecom/templates/ecom/cancel_sellership.html
you already have sellership
wanna cancel it?

Ecom/templates/ecom/confirm_sellership.html
{% load static %}
{% load crispy_forms_tags %}
<html>
<head>
    <meta charset="utf-8">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <link rel="stylesheet" href="{% static '/css/sellership.css'%}">
    <title>Register</title>

</head>
<body>
<div class="rg">
    <div class="content-section mt-4 mb-4 ml-4 mr-4">
        
            <fieldset class="form-group">
                <legend class="border-bottom mb-0">Wanna Become a Seller?</legend>
                <h5 class="text-muted mt-2">Rights and Terms:</h5>
             
                    <small class="text-muted"><i class="fa fa-caret-right"></i> You will Have access to Sell Products.</small><br>
                    <small class="text-muted"><i class="fa fa-caret-right"></i> You will Have a 'Seller' page where you can see the views of your Post.</small><br>    
                    <small class="text-muted"><i class="fa fa-caret-right"></i> You will be able to post 3 images per Product.</small><br>
                
                    <small class="text-muted"><i class="fa fa-caret-right"></i> You will be charged 10€ once you get the Django SellerShip.</small><br>
                    <small class="text-muted"><i class="fa fa-caret-right"></i> You will only receive 98% of the total product value you are selling, We take 2%.</small>
        
            </fieldset>
            <form action ="{% url 'sellership-advise' %}" method ="post">
                {% csrf_token %}
                <div class="btn-group" role="group" aria-label="...">
                    <button class="btn btn-success" type ="submit">Get Django SellerShip</button>
                    <button class="btn btn-primary" type ="submit">10.00 <i class="fa fa-euro"></i></button>    
                         
                </div>
            </form>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Wanna Go back to Homepage? <a class="ml-2" href="{% url 'home' %}">Go Home here</a>
            </small>
        </div>
    </div>
</div>



</body>
</html>

Ecom/templates/ecom/deposit.html
{% extends 'ecom/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<html>
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static '/css/home2.css'%}">
    <link rel="stylesheet" href="{% static '/css/new_product.css'%}">   



<title>Deposit</title>

</head>

<div class="container-fluid defna">
	<nav class="container navbar navbar-expand-lg defna">
	</nav>
</div>



<div class="rp">
    <div class="content-section ml-4 mr-4 mt-4 mb-4">
        <form method="POST" action="{% url 'successful-deposit'%}">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-0">Deposit on Django Comercial</legend>
               
            </fieldset>
                <fieldset class="form-group">
                    {{ cd_form.CardNumber|as_crispy_field }}
                    {{ cd_form.CVV|as_crispy_field }}
                    {{ cd_form.Owner|as_crispy_field }}
                    {{ cd_form.ValidationYear|as_crispy_field }}
                    {{ cd_form.ValidationMonth|as_crispy_field }}
                    {{ cd_form.WithdrawAmount|as_crispy_field }}
                </fieldset>
                <button class="btn btn-success" type="submit">Deposit</button>
        </form>
    </div>
</div>


</body>
</html>

{% endblock content %}

Ecom/templates/ecom/get_sellership.html
{% load static %}
{% load crispy_forms_tags %}
<html>
<head>
    <meta charset="utf-8">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <link rel="stylesheet" href="{% static '/css/sellership.css'%}">
    <title>Register</title>

</head>
<body>
<div class="rg">
    <div class="content-section mt-4 mb-4 ml-4 mr-4">
        
            <fieldset class="form-group">
                <legend class="border-bottom mb-0">Wanna Become a Seller?</legend>
               
            </fieldset>
            <form action="{% url 'confirm-sellership' %}" method ="post">
                {% csrf_token %}
                <div class="btn-group" role="group" aria-label="...">
                    <button class="btn btn-secondary" type ="submit">See Rights and Terms</button>     
                </div>
            </form>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Wanna Go back to Homepage? <a class="ml-2" href="{% url 'home' %}">Go Home here</a>
            </small>
        </div>
    </div>
</div>



</body>
</html>

<script src="/static/js/form.js"></script>

Ecom/templates/ecom/my_orders.html
{% extends 'ecom/base.html' %}
{% load static %}
{% block content %}

<link rel="stylesheet" href="{% static '/css/xs.css'%}">
<link rel="stylesheet" href="{% static '/css/ml.css'%}">
<link rel="stylesheet" href="{% static '/css/mt.css'%}">
<link rel="stylesheet" href="{% static '/css/mt2.css'%}">
<link rel="stylesheet" href="{% static '/css/mt3.css'%}">
<link rel="stylesheet" href="{% static '/css/ml2.css'%}">
<link rel="stylesheet" href="{% static '/css/paddings.css'%}">




    <div style="background-color:rgb(82, 133, 58)" class="container-fluid">
        <nav class="container navbar navbar-expand-lg">
        </nav>
    </div>
    <div class="container pt-5 mt30-">
            <h1>Orders from your Products</h1>
            <hr>      
                <span class="mb-3">Orders</span><span class="pad180">Date</span><span class="pad250">Order Status</span><div class="mt23-" align="center" ><span>{{ order.order_status }}</span></div><div class="mt23- mr-3" align="right"><span>PRICE</span></div>
            <hr>
    
    {% for order in orders %}
                <a href="{% url 'order-detail' order.id %}"> {{ order.order_number }}</a><span class="ml100 text-muted">{{ order.date_placed|date:'l , j M' }}</span>{% if order.order_status == 'Not shipped' %}<div class="mt23- mb-1 text-muted" align="center"><a class="mt33-" style="color:black" href="{% url 'order-detail' order.id %}">{{ order.order_status }}</a>{% else %}<div class="mt23- mb-1 text-muted" align="center"><a class="mt33- text-success" href="{% url 'order-detail' order.id %}">{{ order.order_status }}</a>{% endif %}
    
                </div><div class="mt30-" align="right"><span>{{ order.price_paid }}€</span></div>
    <hr>
    {% endfor %}
{% endblock content %}
</div>

Ecom/templates/ecom/no_items.html
You dont have Items in your cart

Ecom/templates/ecom/order_form.html
{% extends 'ecom/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<html>
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static '/css/armashuski.css'%}">   
    <link rel="stylesheet" href="{% static '/css/payment.css' %}">


<title>Deposit</title>

</head>

<div class="container-fluid defna">
	<nav class="container navbar navbar-expand-lg defna">
	</nav>
</div>
<div class="rp">
    <div class="content-section ml-4 mr-4 mt-4 mb-4">
        
            <fieldset class="form-group">
                <legend class="border-bottom mb-0">What's on your Cart</legend>
               
            </fieldset>
                <fieldset class="form-group">
                    {% for product in cart %}
                      {% if product.item.shipping_price != 0 %}
                        <a href="{% url 'product-detail' product.item.id %}">{{ product.item.title }}</a><font size="2"><span class="ml-2"> Quantity: {{ product.number }}</span></font><font size="3"><span class="text-muted"> - Shipping Price: {{ product.item.shipping_price }}€</span></font><div class="r margin-t"><span style="color:#B12704"><strong>{{ product.true_price }}€ </strong></span></div>
                        <hr>
                      {% else %}  
                        <a href="{% url 'product-detail' product.item.id %}">{{ product.item.title }}</a><font size="2"><span class="ml-2"> Quantity: {{ product.number }}</span></font><font size="3"><span class="text-muted"> - Shipping Price: <span class="text-success"><strong>FREE</strong></span></span></font><div class="r margin-t"><span style="color:#B12704"><strong>{{ product.true_price }}€ </strong></span></div>
                        <hr>                    
                      {% endif %}
                    {% endfor %}    
                <p class="mb-1">Total : <div class="r margin-t2"><span style="color:#B12704"><strong>{{ total }}€</strong></span></div></p>
                </fieldset>
    </div>
</div>
<div class="rp">
    <div class="content-section ml-4 mr-4 mt-4 mb-4">
        <form method="POST" action="{% url 'successful-payment' %}">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-0">Your Address</legend>
               
            </fieldset>
                <fieldset class="form-group">
                   {{ order_form.address_line_1|as_crispy_field }}
                   {{ order_form.address_line_2|as_crispy_field }}
                   {{ order_form.Country|as_crispy_field }}
                   {{ order_form.city|as_crispy_field }}
                   {{ order_form.state|as_crispy_field }}
                   {{ order_form.ZIP_code|as_crispy_field }}
                </fieldset>
                <button class="btn btn-success" type="submit">Place Order</button>
        </form>
    </div>
</div>


</body>
</html>

{% endblock content %}

Ecom/templates/ecom/product_edit_form.html
{% extends 'ecom/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<link rel="stylesheet" href="{% static '/css/new_product.css'%}">


<div class="container-fluid defna">
	<nav class="container navbar navbar-expand-lg defna">
	</nav>
</div>

<div class="rp">
    <div class="content-section ml-4 mr-4 mt-4 mb-4">
        <form method="POST" action="{% url 'confirm-edit' product.id %}"enctype="multipart/form-data">
            {% csrf_token %}
                <fieldset class="form-group">
                    {{ form.title|as_crispy_field }}
                    {{ form.content|as_crispy_field }}
                    {{ form.price|as_crispy_field }}
                    {{ form.shipping_price|as_crispy_field }}
                    {{ form.shipping_time|as_crispy_field }}
                    {{ form.stock|as_crispy_field }}
                    {{ form.image1|as_crispy_field }}
                    {{ form.image2|as_crispy_field }}
                    {{ form.image3|as_crispy_field }}   
                    
                </fieldset>
                <button class="btn btn-success" type="submit">Edit</button>
        </form>
    </div>
</div>

{% endblock content %}

Ecom/templates/ecom/search.html
{% extends 'ecom/base.html'%}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static '/css/cardhome.css'%}">
<link rel="stylesheet" href="{% static '/css/xs.css'%}">

<div style="background-color:rgb(82, 133, 58)" class="container-fluid">
	<nav class="container navbar navbar-expand-lg">
	</nav>
</div>

<div class="container pt-5">
	<form method="POST" action="{% url 'search' %}">
		{% csrf_token %}
		<input class="form-control" style="background-color:white" name="search_text" type="text" placeholder="Search for Products..."></input>
	</form>
	<article> 
		<input class="form-control" style="background-color:rgba(80, 80, 80, 0.267)" id="myInput" onkeyup="myFunction()" type="text" placeholder="Search with more details..."></input>
	</article>



<div class="container mt-5">
	<div class="row">
<ul id="myUL" class="row mr-3">
{% for product in final_list %}
	<liu class="col-md-3">
		<ulx id="{{ product }}">
			<div class="cardv2">
				<a href="{% url 'product-detail' product.id %}"><img src="{{ product.image1.url }}" alt="Avatar" style="width:100%"></a>
					<div class="containerv2">
						<h4 id="{{ product }}title"><b>{{ product.title }}</b></h4> 
						<p> {{ product.price }} €</p> 
					</div>
			</div>
		</ulx>
	</liu>
{% endfor %}		
<ul>

	</div>
</div>

<script src="/static/js/SearchProductBar.js"></script>
<script>
function myFunction() {
    // Declare variables
    var input, filter, ul, li, a, i, txtValue;
    input = document.getElementById('myInput');
    filter = input.value.toUpperCase();
    ul = document.getElementById("myUL");
    li = ul.getElementsByTagName('liu');
  
    // Loop through all list items, and hide those who don't match the search query
    for (i = 0; i < li.length; i++) {
      a = li[i].getElementsByTagName("h4")[0];
      txtValue = a.textContent || a.innerText;
      if (txtValue.toUpperCase().indexOf(filter) > -1) {
        li[i].style.display = "";
      } else {
        li[i].style.display = "none";
      }
    }
  }
var all_products = document.getElementById('myUL');
var products = all_products.getElementsByTagName('ulx');
  
for (z = 0 ; z < products.length ; z++) {
    var pro  = products[z]
    pro = pro.outerHTML
    pro = pro.slice(9)
    var cut_by = pro.indexOf('>')
    pro = pro.slice(0 , cut_by - 1)
    pro = pro + 'title'
    pro_title = document.getElementById(pro)
    text_needed = pro_title.innerHTML
    if (text_needed.length >= 30) {
      text_needed = text_needed.slice(0 , 30)
      document.getElementById(pro).innerHTML = text_needed + '...'
    } else {
         continue
    }
  }
</script>

{% endblock content %}

Ecom/templates/ecom/seller_orders.html
{% extends 'ecom/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

<link rel="stylesheet" href="{% static '/css/xs.css'%}">
<link rel="stylesheet" href="{% static '/css/ml.css'%}">
<link rel="stylesheet" href="{% static '/css/mt.css'%}">
<link rel="stylesheet" href="{% static '/css/mt2.css'%}">
<link rel="stylesheet" href="{% static '/css/mt3.css'%}">
<link rel="stylesheet" href="{% static '/css/ml2.css'%}">
<link rel="stylesheet" href="{% static '/css/paddings.css'%}">




    <div style="background-color:rgb(82, 133, 58)" class="container-fluid">
        <nav class="container navbar navbar-expand-lg">
        </nav>
    </div>
    <div class="container pt-5 mt30-">
            <h1>Orders from your Products</h1>
            <hr>      
                <span class="mb-3">Orders</span><span class="pad180">Date</span><span class="pad250">Order Status</span><div class="mt23-" align="center" ><span>{{ order.order_status }}</span></div><div class="mt23- mr-3" align="right"><span>PRICE</span></div>
            <hr>
    
    {% for order in orders %}
        <a href="{% url 'order-detail' order.id %}"> {{ order.order_number }}</a><span class="ml100 text-muted">{{ order.date_placed|date:'l , j M' }}</span><div class="mt23- text-muted" align="center"><a class="nav-link dropdown-toggle mt33-" style="color:black" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{ order.order_status }}</a><div class="dropdown-menu" aria-labelledby="navbarDropdown"><form method="POST" action="{% url 'tracking-number' order.id %}">{% csrf_token %}<a class="dropdown-item" href="#">


    
    <div id="div_id_tracking_number" class="form-group">
        
            <label for="id_tracking_number" class="">
                {{ order.order_status }}
            </label>
        

        

        

        
            
                <div class="">
                    {% if order.tracking_number != 'Not Provided Yet' %}
                        <input type="text" name="tracking_number" value="{{ order.tracking_number }}" maxlength="200" class="textinput textInput form-control" id="id_tracking_number">
                    {% elif order.tracking_number == 'Not Provided Yet' %}
                        <input type="text" name="tracking_number" value="Not Provided Yet" maxlength="200" class="textinput textInput form-control" id="id_tracking_number">   
                    {% endif %}

    




    



                </div>
            
        
    </div>
    

</a></form></div></div><div class="mt30-" align="right"><span>{{ order.price_paid }}€</span></div>

		
      
      <hr>
    {% endfor %}
</div>
{% endblock content %}

Ecom/templates/ecom/successful_sellership.html
{% load static %}
<html>
<head>
    <meta charset="utf-8">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <link rel="stylesheet" href="{% static '/css/register.css'%}">
    <title>Register</title>

</head>
<body>
<div class="rg">
    <div class="content-section mt-4 mb-4 ml-4 mr-4">
        
            <fieldset class="form-group">
                <legend class="border-bottom mb-0">You are now able to sell Products. Thanks For choosing</legend>
            
            </fieldset>
            <div class="form-group">
               
                <a href="{% url 'home' %}"class="btn btn-info"><i class="fa fa-home fbig"></i> Home</a> <a href="{% url 'new-product' %}"><span class="btn btn-success">Create a new Product Right now!</span></a>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Thanks for choosing us! <a class="ml-2" href="{% url 'home' %}">Back to Homepage</a>
            </small>
        </div>
    </div>
</div>
</body>


</html>

Ecom/templates/ecom/user_cart.html
{% extends 'ecom/base.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static '/css/trying.css'%}">
<link rel="stylesheet" href="{% static '/css/sss.css'%}">


<div class="mt-5">
    <main role="main" class="container">
        <div class="row">
            <div class="col-md-8">
            {% for x in objects_added_to_cart %}
              <article class="media content-section">
                <a href="{% url 'product-detail' x.item.id %}"><img class="" src="{{ x.item.image1.url }}"></a>
                <div class="media-body">
                <div class="article-metadata">
                    <p class="mb-1 ml-2"><a class="mr-2" href="{% url 'product-detail' x.item.id %}">{{ x.item.title }}</a> </p>
                    <small class="text-muted">{{ post.date_posted|date:"F j , Y , H:i" }}</small>
                </div>
                <h3 style="text-align:right;"><a href="{% url 'delete-cart' x.id %}"class="btn btn-danger btn-sm mb-2 mr-3">Remove</a><a id="hello"  class="article-title" href="#">{{ x.item.price }}€</a></h3>
                <h6 style="text-align:right;"><a id="hello"  class="article-title" href="#">Quantity: {{ x.number }}</a></h6>
                {% if x.number > x.item.stock %}
                    <p> There isn't enough items on stock, try ordering less Quantity</p>
                {% endif %}
                </div>
              </article>        
            {% endfor %}
            </div>
            <div class="col-md-4">
            <div class="content-section">
                <h3>Our Sidebar</h3>
                <p class='text-muted'>
                <ul class="list-group">
                    <p href="#" style="color:black" class="list-group-item list-group-item-light">Total price: <span style="color:#B12704"><strong>{{ checkout_price }}€ </strong></span><font size="2"><span class="text-muted">+ {{ checkout_shipping_price }}€</span></font></p> 
                    <a href="{% url 'proceed-payment' %}" class="list-group-item list-group-item-light lol"><b>Proceed to Payment</b></a>
                </ul>
                </p>
            </div>
            </div>
        </div>
        </main>
</div>
{% endblock content%}

Ecom/templates/ecom/warning_sellership.html
You dont have Sellership